name: Publish WorkFlow

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: 🐍 Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: 🦾 Install dependencies
        run: |
          python -m pip install --upgrade virtualenv
          python -m pip install --upgrade pip
          virtualenv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          python -m pip install --upgrade poetry
          poetry install

      - name:  🏗️ Build source and wheel distributions
        run: |
          python -m pip install --upgrade build twine
          python -m build
          twine check --strict dist/*
      - name: 🚀 Publish to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: ${{ secrets.PYPI_USERNAME }}
          password: ${{ secrets.PYPI_PASSWORD }}
      - name: 🚀 Publish to Test-PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          user: ${{ secrets.PYPI_USERNAME }}
          password: ${{ secrets.PYPI_TEST_PASSWORD }}
